### ISSUE TITLE
Photo's Gone

### ISSUE THREAD

**Issue by jktantan14** [xibalba10/plugin.video.xxx-o-dus#11]
Hello,

I was wondering what happen to the Photos option, it's gone. Did you remove it, if so, do you plan to bring it back?

 It was my favorite part of the app because it was unique to it. Video apps are much more common.

**Comment by xibalba10** [comment]
Hello,

XXX-O-DUS has been completly rewritten and side by side with this I have been spending a lot of time on the resolvers for the sites also.

Due to this certain things at the moment are missing and may or may not come back in.

What I can say is XXX-O-DUS and its scrpaers are having daily updates are more stuff is added back in so keep checking and they may reappear.

If you have any more questions please ask. I will close the issue if I do not head back in the next 24 hours.

Thanks again.

**Comment by xibalba10** [comment]
Pictures have been added with motherless starting the section. More will be added over the coming, days and weeks. Any other issues please raise another issue.
