### ISSUE TITLE
Movies Tab

### ISSUE THREAD

**Issue by LezzLover** [xibalba10/plugin.video.xxx-o-dus#9]
What happened to the movies tab, my favourite. its not showing in this new version.

**Comment by xibalba10** [comment]
Hello,

XXX-O-DUS has been completly rewritten and side by side with this I have been spending a lot of time on the resolvers for the sites also.

Due to this certain things at the moment are missing and may or may not come back in.

What I can say is XXX-O-DUS and its scrpaers are having daily updates are more stuff is added back in so keep checking and they may reappear.

If you have any more questions please ask. I will close the issue if I do not head back in the next 24 hours.

Thanks again.

**Comment by xibalba10** [comment]
I have added a 'scenes' section to the menu that contains scenes. More will be added over the coming weeks if I find more. Any other issues please raise a new issue. Thanks
